//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBackupFile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Directories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Directories"]));
            }
            set {
                this["Directories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupName {
            get {
                return ((string)(this["BackupName"]));
            }
            set {
                this["BackupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveTo {
            get {
                return ((string)(this["SaveTo"]));
            }
            set {
                this["SaveTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto {
            get {
                return ((bool)(this["Auto"]));
            }
            set {
                this["Auto"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>B4-2E-99-64-02-3C</string>
  <string>50-9A-4C-6B-B8-5D</string>
  <string>50-9A-4C-6B-B8-5E</string>
  <string>18-66-DA-43-FC-C3</string>
  <string>00-FF-9A-0C-BA-63</string>
  <string>A4-BB-6D-B2-AB-3A</string>
  <string>E4-54-E8-6D-AA-38</string>
  <string>00-FF-97-C6-30-CC</string>
  <string>44-39-C4-37-65-8B</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Registered {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Registered"]));
            }
        }
    }
}
